image: docker:latest
services:
  - docker:dind

stages:
  - build

build:
  stage: build
  script:
    - docker build --pull -t selkie-build-image utils/ci
    - docker run --rm -v ./:/workspace:rw selkie-build-image "mkdir /workspace/build && cd /workspace/build && cmake ../ && cmake --build"