image: docker:latest

services:
  - name: docker:dind
    command: ["--tls=false"]

stages:
  - build

variables:
  DOCKER_TLS_CERTDIR: ""
  GIT_SUBMODULE_STRATEGY: recursive

build:
  stage: build
  script:
    - "docker build --pull -t selkie-build-image utils/ci"
    - "mkdir build"
    - "docker run --rm -v ./:/workspace:rw selkie-build-image 
      /bin/bash -c \"cd /workspace/build && cmake -DCMAKE_BUILD_TYPE=Release ../ && cmake --build .\""
  artifacts:
    paths:
      - build/apps/console_client/SelkieConsoleClient
      - build/apps/gui_server/SelkieGUIServer
      - build/apps/server/SelkieServer
